ダークモード時のcode styleの背景色と文字色が同系色になる問題の修正
Nishihara-Daiki/chat-helper pull request #1
Opened 2021-09-13 10:58 UTC by lockn-yamada

ダークモードで使用しているとき，markdownのcode styleを使用すると，背景色も文字色も白系統の色になってしまい，見にくかったので修正しました。

ダークモード時には #303030 になるようにしています。

色や変数名等，不都合があればご指摘 or 修正していただけると助かります。

2021-09-13 15:31 UTC, Nishihara-Daiki requested changes
PRありがとうございます！
本件、いつか修正をと思いつつも立て込んで保留になっているところでした。

※余談ですが、手元の修正したいリストでは、code style の複数テーマ選択（＝ダークモード系も選べるようになる）も近いうちに実装したい機能の一つとして積まれています... 近いうちに...

2021-09-13 15:31 UTC, Nishihara-Daiki commented on src/content_scripts/style.css
> +@media (prefers-color-scheme: dark) {
テーマ設定の判定は、OS側のダークモード設定（と推察しておりますが、誤っていたらすみません）`@media (prefers-color-scheme: dark)` よりも、google chat 側のダークモード設定（恐らくCSSセレクタ `[data-theme="dark"]` で拾えると予想しています）を用いる方が妥当かと思います。

2021-09-14 12:29 UTC, lockn-yamada commented on src/content_scripts/style.css
> +@media (prefers-color-scheme: dark) {
おっしゃるとおりですね！(OSをダークモードにしたまま，google chatのテーマをlightにしても背景色が暗いままになってしまってました)  

`[data-theme="dark"]` を使用するように変更しました。

2021-09-14 12:35 UTC, lockn-yamada commented
こちらの拡張機能，大変便利に使わせていただいています！  
もしテーマ選択等，別の機能でこの問題に対応される予定でしたら，マージは見送りでも大丈夫です 🙇

2021-09-14 15:09 UTC, Nishihara-Daiki approved these changes
LGTM

2021-09-14 15:10 UTC, merged